title: "My Creative Space" # Replace this with your desired blog name
description: "Sharing projects, reflections, and ideas"
footer: "Powered by GitHub Pages | Inspired by creativity 🌟" # Replace this with your footer content
