theme: minima
minima:
  skin: pastel
  social_links: 
    github: "https://github.com/famu8"
    linkedin: "https://www.linkedin.com/in/fernandomarinaurriola/"

author:
feed:
  enabled: false

title: "famu8 blog"
description: "Sharing projects, reflections, and ideas"
